package com.qt.webframe.system.pojo;

import java.util.Date;

public class Auth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_auth.authid
     *
     * @mbg.generated
     */
    private String authid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_auth.authtype
     *
     * @mbg.generated
     */
    private String authtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_auth.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_auth.createuserid
     *
     * @mbg.generated
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_auth.createdatetime
     *
     * @mbg.generated
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_auth.updateuserid
     *
     * @mbg.generated
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_auth.updatedatetime
     *
     * @mbg.generated
     */
    private Date updatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_auth.authid
     *
     * @return the value of t_bd_auth.authid
     *
     * @mbg.generated
     */
    public String getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_auth.authid
     *
     * @param authid the value for t_bd_auth.authid
     *
     * @mbg.generated
     */
    public void setAuthid(String authid) {
        this.authid = authid == null ? null : authid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_auth.authtype
     *
     * @return the value of t_bd_auth.authtype
     *
     * @mbg.generated
     */
    public String getAuthtype() {
        return authtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_auth.authtype
     *
     * @param authtype the value for t_bd_auth.authtype
     *
     * @mbg.generated
     */
    public void setAuthtype(String authtype) {
        this.authtype = authtype == null ? null : authtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_auth.isdel
     *
     * @return the value of t_bd_auth.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_auth.isdel
     *
     * @param isdel the value for t_bd_auth.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_auth.createuserid
     *
     * @return the value of t_bd_auth.createuserid
     *
     * @mbg.generated
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_auth.createuserid
     *
     * @param createuserid the value for t_bd_auth.createuserid
     *
     * @mbg.generated
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_auth.createdatetime
     *
     * @return the value of t_bd_auth.createdatetime
     *
     * @mbg.generated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_auth.createdatetime
     *
     * @param createdatetime the value for t_bd_auth.createdatetime
     *
     * @mbg.generated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_auth.updateuserid
     *
     * @return the value of t_bd_auth.updateuserid
     *
     * @mbg.generated
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_auth.updateuserid
     *
     * @param updateuserid the value for t_bd_auth.updateuserid
     *
     * @mbg.generated
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_auth.updatedatetime
     *
     * @return the value of t_bd_auth.updatedatetime
     *
     * @mbg.generated
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_auth.updatedatetime
     *
     * @param updatedatetime the value for t_bd_auth.updatedatetime
     *
     * @mbg.generated
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }
}