package com.qt.webframe.system.pojo;

import java.util.Date;

public class Opt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.optid
     *
     * @mbg.generated
     */
    private String optid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.optname
     *
     * @mbg.generated
     */
    private String optname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.optcode
     *
     * @mbg.generated
     */
    private String optcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.preurl
     *
     * @mbg.generated
     */
    private String preurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.parentid
     *
     * @mbg.generated
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.isdistribute
     *
     * @mbg.generated
     */
    private Boolean isdistribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.createuserid
     *
     * @mbg.generated
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.createdatetime
     *
     * @mbg.generated
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.updateuserid
     *
     * @mbg.generated
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_opt.updatedatetime
     *
     * @mbg.generated
     */
    private Date updatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.optid
     *
     * @return the value of t_bd_opt.optid
     *
     * @mbg.generated
     */
    public String getOptid() {
        return optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.optid
     *
     * @param optid the value for t_bd_opt.optid
     *
     * @mbg.generated
     */
    public void setOptid(String optid) {
        this.optid = optid == null ? null : optid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.optname
     *
     * @return the value of t_bd_opt.optname
     *
     * @mbg.generated
     */
    public String getOptname() {
        return optname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.optname
     *
     * @param optname the value for t_bd_opt.optname
     *
     * @mbg.generated
     */
    public void setOptname(String optname) {
        this.optname = optname == null ? null : optname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.optcode
     *
     * @return the value of t_bd_opt.optcode
     *
     * @mbg.generated
     */
    public String getOptcode() {
        return optcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.optcode
     *
     * @param optcode the value for t_bd_opt.optcode
     *
     * @mbg.generated
     */
    public void setOptcode(String optcode) {
        this.optcode = optcode == null ? null : optcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.preurl
     *
     * @return the value of t_bd_opt.preurl
     *
     * @mbg.generated
     */
    public String getPreurl() {
        return preurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.preurl
     *
     * @param preurl the value for t_bd_opt.preurl
     *
     * @mbg.generated
     */
    public void setPreurl(String preurl) {
        this.preurl = preurl == null ? null : preurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.parentid
     *
     * @return the value of t_bd_opt.parentid
     *
     * @mbg.generated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.parentid
     *
     * @param parentid the value for t_bd_opt.parentid
     *
     * @mbg.generated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.isdistribute
     *
     * @return the value of t_bd_opt.isdistribute
     *
     * @mbg.generated
     */
    public Boolean getIsdistribute() {
        return isdistribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.isdistribute
     *
     * @param isdistribute the value for t_bd_opt.isdistribute
     *
     * @mbg.generated
     */
    public void setIsdistribute(Boolean isdistribute) {
        this.isdistribute = isdistribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.isdel
     *
     * @return the value of t_bd_opt.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.isdel
     *
     * @param isdel the value for t_bd_opt.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.createuserid
     *
     * @return the value of t_bd_opt.createuserid
     *
     * @mbg.generated
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.createuserid
     *
     * @param createuserid the value for t_bd_opt.createuserid
     *
     * @mbg.generated
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.createdatetime
     *
     * @return the value of t_bd_opt.createdatetime
     *
     * @mbg.generated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.createdatetime
     *
     * @param createdatetime the value for t_bd_opt.createdatetime
     *
     * @mbg.generated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.updateuserid
     *
     * @return the value of t_bd_opt.updateuserid
     *
     * @mbg.generated
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.updateuserid
     *
     * @param updateuserid the value for t_bd_opt.updateuserid
     *
     * @mbg.generated
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_opt.updatedatetime
     *
     * @return the value of t_bd_opt.updatedatetime
     *
     * @mbg.generated
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_opt.updatedatetime
     *
     * @param updatedatetime the value for t_bd_opt.updatedatetime
     *
     * @mbg.generated
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }
}