package com.qt.webframe.system.pojo;

public class Params {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_params.paramcode
     *
     * @mbg.generated
     */
    private String paramcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_params.paramtype
     *
     * @mbg.generated
     */
    private String paramtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_params.paramdesc
     *
     * @mbg.generated
     */
    private String paramdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_params.paramvalue
     *
     * @mbg.generated
     */
    private String paramvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_params.paramcode
     *
     * @return the value of t_sys_params.paramcode
     *
     * @mbg.generated
     */
    public String getParamcode() {
        return paramcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_params.paramcode
     *
     * @param paramcode the value for t_sys_params.paramcode
     *
     * @mbg.generated
     */
    public void setParamcode(String paramcode) {
        this.paramcode = paramcode == null ? null : paramcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_params.paramtype
     *
     * @return the value of t_sys_params.paramtype
     *
     * @mbg.generated
     */
    public String getParamtype() {
        return paramtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_params.paramtype
     *
     * @param paramtype the value for t_sys_params.paramtype
     *
     * @mbg.generated
     */
    public void setParamtype(String paramtype) {
        this.paramtype = paramtype == null ? null : paramtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_params.paramdesc
     *
     * @return the value of t_sys_params.paramdesc
     *
     * @mbg.generated
     */
    public String getParamdesc() {
        return paramdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_params.paramdesc
     *
     * @param paramdesc the value for t_sys_params.paramdesc
     *
     * @mbg.generated
     */
    public void setParamdesc(String paramdesc) {
        this.paramdesc = paramdesc == null ? null : paramdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_params.paramvalue
     *
     * @return the value of t_sys_params.paramvalue
     *
     * @mbg.generated
     */
    public String getParamvalue() {
        return paramvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_params.paramvalue
     *
     * @param paramvalue the value for t_sys_params.paramvalue
     *
     * @mbg.generated
     */
    public void setParamvalue(String paramvalue) {
        this.paramvalue = paramvalue == null ? null : paramvalue.trim();
    }
}