package com.qt.webframe.system.pojo;

public class R_dept_user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_user.deptid
     *
     * @mbg.generated
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_user.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_user.id
     *
     * @return the value of r_dept_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_user.id
     *
     * @param id the value for r_dept_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_user.deptid
     *
     * @return the value of r_dept_user.deptid
     *
     * @mbg.generated
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_user.deptid
     *
     * @param deptid the value for r_dept_user.deptid
     *
     * @mbg.generated
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_user.userid
     *
     * @return the value of r_dept_user.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_user.userid
     *
     * @param userid the value for r_dept_user.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}