package com.qt.webframe.system.pojo;

public class R_user_role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.roleid
     *
     * @mbg.generated
     */
    private String roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.id
     *
     * @return the value of r_user_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.id
     *
     * @param id the value for r_user_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.userid
     *
     * @return the value of r_user_role.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.userid
     *
     * @param userid the value for r_user_role.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.roleid
     *
     * @return the value of r_user_role.roleid
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.roleid
     *
     * @param roleid the value for r_user_role.roleid
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }
}