package com.qt.webframe.system.pojo;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.username
     *
     * @mbg.generated
     */
    @NotNull(message = "{user.name.notnull}")
    @Length(max = 20, message = "{user.name.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{user.name.formaterr}")
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.password
     *
     * @mbg.generated
     */
    @NotNull(message = "{user.password.notnull}")
    @Length(min = 6, max = 20, message = "{user.password.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{user.password.formaterr}")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.nickname
     *
     * @mbg.generated
     */
    @NotNull(message = "{user.nickname.notnull}")
    @Length(max = 16, message = "{user.nickname.formaterr}")
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.phonenum
     *
     * @mbg.generated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.birthdate
     *
     * @mbg.generated
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.isforbidden
     *
     * @mbg.generated
     */
    private Boolean isforbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.createuserid
     *
     * @mbg.generated
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.createdatetime
     *
     * @mbg.generated
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.updateuserid
     *
     * @mbg.generated
     */
    private String updateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_user.updatedatetime
     *
     * @mbg.generated
     */
    private Date updatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.userid
     *
     * @return the value of t_bd_user.userid
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.userid
     *
     * @param userid the value for t_bd_user.userid
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.username
     *
     * @return the value of t_bd_user.username
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.username
     *
     * @param username the value for t_bd_user.username
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.password
     *
     * @return the value of t_bd_user.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.password
     *
     * @param password the value for t_bd_user.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.nickname
     *
     * @return the value of t_bd_user.nickname
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.nickname
     *
     * @param nickname the value for t_bd_user.nickname
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.phonenum
     *
     * @return the value of t_bd_user.phonenum
     * @mbg.generated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.phonenum
     *
     * @param phonenum the value for t_bd_user.phonenum
     * @mbg.generated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.email
     *
     * @return the value of t_bd_user.email
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.email
     *
     * @param email the value for t_bd_user.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.sex
     *
     * @return the value of t_bd_user.sex
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.sex
     *
     * @param sex the value for t_bd_user.sex
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.birthdate
     *
     * @return the value of t_bd_user.birthdate
     * @mbg.generated
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.birthdate
     *
     * @param birthdate the value for t_bd_user.birthdate
     * @mbg.generated
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.realname
     *
     * @return the value of t_bd_user.realname
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.realname
     *
     * @param realname the value for t_bd_user.realname
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.province
     *
     * @return the value of t_bd_user.province
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.province
     *
     * @param province the value for t_bd_user.province
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.city
     *
     * @return the value of t_bd_user.city
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.city
     *
     * @param city the value for t_bd_user.city
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.address
     *
     * @return the value of t_bd_user.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.address
     *
     * @param address the value for t_bd_user.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.isforbidden
     *
     * @return the value of t_bd_user.isforbidden
     * @mbg.generated
     */
    public Boolean getIsforbidden() {
        return isforbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.isforbidden
     *
     * @param isforbidden the value for t_bd_user.isforbidden
     * @mbg.generated
     */
    public void setIsforbidden(Boolean isforbidden) {
        this.isforbidden = isforbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.isdel
     *
     * @return the value of t_bd_user.isdel
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.isdel
     *
     * @param isdel the value for t_bd_user.isdel
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.createuserid
     *
     * @return the value of t_bd_user.createuserid
     * @mbg.generated
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.createuserid
     *
     * @param createuserid the value for t_bd_user.createuserid
     * @mbg.generated
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.createdatetime
     *
     * @return the value of t_bd_user.createdatetime
     * @mbg.generated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.createdatetime
     *
     * @param createdatetime the value for t_bd_user.createdatetime
     * @mbg.generated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.updateuserid
     *
     * @return the value of t_bd_user.updateuserid
     * @mbg.generated
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.updateuserid
     *
     * @param updateuserid the value for t_bd_user.updateuserid
     * @mbg.generated
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_user.updatedatetime
     *
     * @return the value of t_bd_user.updatedatetime
     * @mbg.generated
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_user.updatedatetime
     *
     * @param updatedatetime the value for t_bd_user.updatedatetime
     * @mbg.generated
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }
}