package com.qt.webframe.system.pojo;

import java.util.Date;

public class UToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_usertoken.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_usertoken.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_usertoken.createdatetime
     *
     * @mbg.generated
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_usertoken.expirydate
     *
     * @mbg.generated
     */
    private Integer expirydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_usertoken.userid
     *
     * @return the value of t_sys_usertoken.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_usertoken.userid
     *
     * @param userid the value for t_sys_usertoken.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_usertoken.token
     *
     * @return the value of t_sys_usertoken.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_usertoken.token
     *
     * @param token the value for t_sys_usertoken.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_usertoken.createdatetime
     *
     * @return the value of t_sys_usertoken.createdatetime
     *
     * @mbg.generated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_usertoken.createdatetime
     *
     * @param createdatetime the value for t_sys_usertoken.createdatetime
     *
     * @mbg.generated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_usertoken.expirydate
     *
     * @return the value of t_sys_usertoken.expirydate
     *
     * @mbg.generated
     */
    public Integer getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_usertoken.expirydate
     *
     * @param expirydate the value for t_sys_usertoken.expirydate
     *
     * @mbg.generated
     */
    public void setExpirydate(Integer expirydate) {
        this.expirydate = expirydate;
    }
}