package com.qt.webframe.crm.dao;

import com.qt.webframe.crm.pojo.Product;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_product
     *
     * @mbg.generated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    List<Product> selectProListByStr(Map<String, Object> map, int start, int length);

    Product selectByProNo(String productno);
}