package com.qt.webframe.crm.dao;

import com.qt.webframe.crm.pojo.R_dept_cust;
import org.springframework.stereotype.Repository;

@Repository
public interface R_dept_custMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_cust
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_cust
     *
     * @mbg.generated
     */
    int insert(R_dept_cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_cust
     *
     * @mbg.generated
     */
    int insertSelective(R_dept_cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_cust
     *
     * @mbg.generated
     */
    R_dept_cust selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_cust
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(R_dept_cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_cust
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(R_dept_cust record);
}