package com.qt.webframe.crm.dao;

import com.qt.webframe.crm.pojo.Server;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_server
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String serverid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_server
     *
     * @mbg.generated
     */
    int insert(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_server
     *
     * @mbg.generated
     */
    int insertSelective(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_server
     *
     * @mbg.generated
     */
    Server selectByPrimaryKey(String serverid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Server record);

    Server selectByServerNo(String serverNo);

    List<Server> selectServListByStr(Map<String, Object> map, int start, int length);

    List<Server> selectDeptServListByStr(Map<String, Object> map, int start, int length);
}