package com.qt.webframe.crm.dao;

import com.qt.webframe.crm.pojo.Trade;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_trade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_trade
     *
     * @mbg.generated
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_trade
     *
     * @mbg.generated
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_trade
     *
     * @mbg.generated
     */
    Trade selectByPrimaryKey(String tradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_trade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_trade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Trade record);

    List<Trade> selectTraListByStr(Map<String, Object> map, int start, int length);

    Trade selectByTradeNo(String tradeno);

    List<Trade> selectDeptTraListByStr(Map<String, Object> map, int start, int length);
}