package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Auth;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String authid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_auth
     *
     * @mbg.generated
     */
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_auth
     *
     * @mbg.generated
     */
    int insertSelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_auth
     *
     * @mbg.generated
     */
    Auth selectByPrimaryKey(String authid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Auth record);

}