package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Department;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_department
     *
     * @mbg.generated
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_department
     *
     * @mbg.generated
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_department
     *
     * @mbg.generated
     */
    Department selectByPrimaryKey(String deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Department record);

    Department selectByDeptNo(String deptNo);

    Department selectByDeptName(String deptName);

    List<Department> selectDeptListByStr(Map<String, Object> map, int start, int length);
}