package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Menu;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_menu
     *
     * @mbg.generated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_menu
     *
     * @mbg.generated
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_menu
     *
     * @mbg.generated
     */
    Menu selectByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Menu record);

    List<Menu> selectUserMenusByUserId(String userid);
}