package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Opt;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_opt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String optid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_opt
     *
     * @mbg.generated
     */
    int insert(Opt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_opt
     *
     * @mbg.generated
     */
    int insertSelective(Opt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_opt
     *
     * @mbg.generated
     */
    Opt selectByPrimaryKey(String optid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_opt
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Opt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_opt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Opt record);

    List<Opt> selectUserOptListByUserid(String userid);
}