package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Organization;
import org.springframework.stereotype.Repository;

@Repository
public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_organization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_organization
     *
     * @mbg.generated
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_organization
     *
     * @mbg.generated
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_organization
     *
     * @mbg.generated
     */
    Organization selectByPrimaryKey(String orgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Organization record);

    Organization selectCurrentOrg();
}