package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Params;
import org.springframework.stereotype.Repository;

@Repository
public interface ParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_params
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String paramcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_params
     *
     * @mbg.generated
     */
    int insert(Params record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_params
     *
     * @mbg.generated
     */
    int insertSelective(Params record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_params
     *
     * @mbg.generated
     */
    Params selectByPrimaryKey(String paramcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_params
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Params record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_params
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Params record);
}