package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.R_dept_user;
import org.springframework.stereotype.Repository;

@Repository
public interface R_dept_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_user
     *
     * @mbg.generated
     */
    int insert(R_dept_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_user
     *
     * @mbg.generated
     */
    int insertSelective(R_dept_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_user
     *
     * @mbg.generated
     */
    R_dept_user selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(R_dept_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dept_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(R_dept_user record);

    R_dept_user selectByUserId(String userid);
}