package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.R_user_role;
import org.springframework.stereotype.Repository;

@Repository
public interface R_user_roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int insert(R_user_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int insertSelective(R_user_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    R_user_role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(R_user_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(R_user_role record);
}