package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Role;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_role
     *
     * @mbg.generated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_role
     *
     * @mbg.generated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_role
     *
     * @mbg.generated
     */
    Role selectByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Role record);

    /**
     * 根据角色名称查找角色id
     * @param roleName
     * @return
     */
    Role selectRoleIdByName(String roleName);
}