package com.qt.webframe.system.dao;

import com.qt.webframe.system.pojo.Department;
import com.qt.webframe.system.pojo.User;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
    /**
     * 通过用户名密码查找用户
     * @param username
     * @param password
     * @return
     */
    User selectByUsernamePassword(String username, String password);

    /**
     * 通过用户名查找用户
     * @param username
     * @return
     */
    User selectByUsername(String username);

    /**
     *
     * @param map
     * @param start
     * @param length
     * @return
     */
    List<User> selectOrgUserListByStr(Map<String,Object> map, int start, int length);

    List<User> selectNoDeptUserListByStr(Map<String, Object> map, int start, int length);

    List<User> selectDeptUserListByStr(Map<String, Object> map, int start, int length);
}