package com.qt.webframe.crm.pojo;

public class R_dept_trade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_trade.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_trade.deptid
     *
     * @mbg.generated
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_trade.tradeid
     *
     * @mbg.generated
     */
    private String tradeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_trade.id
     *
     * @return the value of r_dept_trade.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_trade.id
     *
     * @param id the value for r_dept_trade.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_trade.deptid
     *
     * @return the value of r_dept_trade.deptid
     *
     * @mbg.generated
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_trade.deptid
     *
     * @param deptid the value for r_dept_trade.deptid
     *
     * @mbg.generated
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_trade.tradeid
     *
     * @return the value of r_dept_trade.tradeid
     *
     * @mbg.generated
     */
    public String getTradeid() {
        return tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_trade.tradeid
     *
     * @param tradeid the value for r_dept_trade.tradeid
     *
     * @mbg.generated
     */
    public void setTradeid(String tradeid) {
        this.tradeid = tradeid == null ? null : tradeid.trim();
    }
}