package com.qt.webframe.crm.pojo;

public class R_dept_cust {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_cust.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_cust.deptid
     *
     * @mbg.generated
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dept_cust.customerid
     *
     * @mbg.generated
     */
    private String customerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_cust.id
     *
     * @return the value of r_dept_cust.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_cust.id
     *
     * @param id the value for r_dept_cust.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_cust.deptid
     *
     * @return the value of r_dept_cust.deptid
     *
     * @mbg.generated
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_cust.deptid
     *
     * @param deptid the value for r_dept_cust.deptid
     *
     * @mbg.generated
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dept_cust.customerid
     *
     * @return the value of r_dept_cust.customerid
     *
     * @mbg.generated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dept_cust.customerid
     *
     * @param customerid the value for r_dept_cust.customerid
     *
     * @mbg.generated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }
}