package com.qt.webframe.crm.pojo;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.util.Date;

public class Server {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.serverid
     *
     * @mbg.generated
     */
    private String serverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.serverNo
     *
     * @mbg.generated
     */
    @NotNull(message = "{serv.no.notnull}")
    @Length(max = 20, message = "{serv.no.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{serv.no.formaterr}")
    private String serverno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.tradeNo
     *
     * @mbg.generated
     */
    @NotNull(message = "{trade.no.notnull}")
    @Length(max = 20, message = "{trade.no.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{trade.no.formaterr}")
    private String tradeno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.startdate
     *
     * @mbg.generated
     */
    @NotNull(message = "{serv.sdate.notnull}")
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.enddate
     *
     * @mbg.generated
     */
    @NotNull(message = "{serv.edate.notnull}")
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.servertype
     *
     * @mbg.generated
     */
    @NotNull(message = "{serv.type.notnull}")
    @Length(max = 50, message = "{serv.type.formaterr}")
    private String servertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.content
     *
     * @mbg.generated
     */
    @NotNull(message = "{serv.content.notnull}")
    @Length(max = 200, message = "{serv.content.formaterr}")
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.validitydate
     *
     * @mbg.generated
     */
    private Date validitydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.servUsername
     *
     * @mbg.generated
     */
    @NotNull(message = "{serv.uname.notnull}")
    @Length(max = 20, message = "{serv.uname.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{serv.uname.formaterr}")
    private String servusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.relax
     *
     * @mbg.generated
     */
    @NotNull(message = "{cust.relax.notnull}")
    @Length(max = 16, message = "{cust.relax.formaterr}")
    private String relax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.telphone
     *
     * @mbg.generated
     */
    @NotNull(message = "{cust.tel.notnull}")
    @Length(max = 16, message = "{cust.tel.formaterr}")
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.createuserid
     *
     * @mbg.generated
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.createdatetime
     *
     * @mbg.generated
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.updateuserid
     *
     * @mbg.generated
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_server.updatedatetime
     *
     * @mbg.generated
     */
    private Date updatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.serverid
     *
     * @return the value of t_crm_server.serverid
     *
     * @mbg.generated
     */
    public String getServerid() {
        return serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.serverid
     *
     * @param serverid the value for t_crm_server.serverid
     *
     * @mbg.generated
     */
    public void setServerid(String serverid) {
        this.serverid = serverid == null ? null : serverid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.serverNo
     *
     * @return the value of t_crm_server.serverNo
     *
     * @mbg.generated
     */
    public String getServerno() {
        return serverno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.serverNo
     *
     * @param serverno the value for t_crm_server.serverNo
     *
     * @mbg.generated
     */
    public void setServerno(String serverno) {
        this.serverno = serverno == null ? null : serverno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.tradeNo
     *
     * @return the value of t_crm_server.tradeNo
     *
     * @mbg.generated
     */
    public String getTradeno() {
        return tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.tradeNo
     *
     * @param tradeno the value for t_crm_server.tradeNo
     *
     * @mbg.generated
     */
    public void setTradeno(String tradeno) {
        this.tradeno = tradeno == null ? null : tradeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.startdate
     *
     * @return the value of t_crm_server.startdate
     *
     * @mbg.generated
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.startdate
     *
     * @param startdate the value for t_crm_server.startdate
     *
     * @mbg.generated
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.enddate
     *
     * @return the value of t_crm_server.enddate
     *
     * @mbg.generated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.enddate
     *
     * @param enddate the value for t_crm_server.enddate
     *
     * @mbg.generated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.servertype
     *
     * @return the value of t_crm_server.servertype
     *
     * @mbg.generated
     */
    public String getServertype() {
        return servertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.servertype
     *
     * @param servertype the value for t_crm_server.servertype
     *
     * @mbg.generated
     */
    public void setServertype(String servertype) {
        this.servertype = servertype == null ? null : servertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.content
     *
     * @return the value of t_crm_server.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.content
     *
     * @param content the value for t_crm_server.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.amount
     *
     * @return the value of t_crm_server.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.amount
     *
     * @param amount the value for t_crm_server.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.validitydate
     *
     * @return the value of t_crm_server.validitydate
     *
     * @mbg.generated
     */
    public Date getValiditydate() {
        return validitydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.validitydate
     *
     * @param validitydate the value for t_crm_server.validitydate
     *
     * @mbg.generated
     */
    public void setValiditydate(Date validitydate) {
        this.validitydate = validitydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.servUsername
     *
     * @return the value of t_crm_server.servUsername
     *
     * @mbg.generated
     */
    public String getServusername() {
        return servusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.servUsername
     *
     * @param servusername the value for t_crm_server.servUsername
     *
     * @mbg.generated
     */
    public void setServusername(String servusername) {
        this.servusername = servusername == null ? null : servusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.relax
     *
     * @return the value of t_crm_server.relax
     *
     * @mbg.generated
     */
    public String getRelax() {
        return relax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.relax
     *
     * @param relax the value for t_crm_server.relax
     *
     * @mbg.generated
     */
    public void setRelax(String relax) {
        this.relax = relax == null ? null : relax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.telphone
     *
     * @return the value of t_crm_server.telphone
     *
     * @mbg.generated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.telphone
     *
     * @param telphone the value for t_crm_server.telphone
     *
     * @mbg.generated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.remark
     *
     * @return the value of t_crm_server.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.remark
     *
     * @param remark the value for t_crm_server.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.isdel
     *
     * @return the value of t_crm_server.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.isdel
     *
     * @param isdel the value for t_crm_server.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.createuserid
     *
     * @return the value of t_crm_server.createuserid
     *
     * @mbg.generated
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.createuserid
     *
     * @param createuserid the value for t_crm_server.createuserid
     *
     * @mbg.generated
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.createdatetime
     *
     * @return the value of t_crm_server.createdatetime
     *
     * @mbg.generated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.createdatetime
     *
     * @param createdatetime the value for t_crm_server.createdatetime
     *
     * @mbg.generated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.updateuserid
     *
     * @return the value of t_crm_server.updateuserid
     *
     * @mbg.generated
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.updateuserid
     *
     * @param updateuserid the value for t_crm_server.updateuserid
     *
     * @mbg.generated
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_server.updatedatetime
     *
     * @return the value of t_crm_server.updatedatetime
     *
     * @mbg.generated
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_server.updatedatetime
     *
     * @param updatedatetime the value for t_crm_server.updatedatetime
     *
     * @mbg.generated
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }
}