package com.qt.webframe.crm.pojo;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.util.Date;

public class Trade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.tradeId
     *
     * @mbg.generated
     */
    private String tradeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.tradeNo
     *
     * @mbg.generated
     */
    @NotNull(message = "{trade.no.notnull}")
    @Length(max = 20, message = "{trade.no.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{trade.no.formaterr}")
    private String tradeno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.customerNo
     *
     * @mbg.generated
     */
    @NotNull(message = "{cust.no.notnull}")
    @Length(max = 20, message = "{cust.no.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{cust.no.formaterr}")
    private String customerno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.productNo
     *
     * @mbg.generated
     */
    @NotNull(message = "{pro.no.notnull}")
    @Length(max = 20, message = "{pro.no.formaterr}")
    @Pattern(regexp = "^[A-Za-z0-9]+$", message = "{pro.no.formaterr}")
    private String productno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.modules
     *
     * @mbg.generated
     */
    @NotNull(message = "{trade.module.notnull}")
    @Length(max = 100, message = "{trade.module.formaterr}")
    private String modules;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.count
     *
     * @mbg.generated
     */
    @NotNull(message = "{trade.count.notnull}")
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.amount
     *
     * @mbg.generated
     */
    @NotNull(message = "{trade.amount.notnull}")
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.freeServer
     *
     * @mbg.generated
     */
    @NotNull(message = "{trade.freeserver.notnull}")
    private Date freeserver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.serialnumber
     *
     * @mbg.generated
     */
    private String serialnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.cdkey
     *
     * @mbg.generated
     */
    private String cdkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.signatures
     *
     * @mbg.generated
     */
    private String signatures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.encryptiontype
     *
     * @mbg.generated
     */
    private String encryptiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.voucherpapertype
     *
     * @mbg.generated
     */
    private String voucherpapertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.tradedate
     *
     * @mbg.generated
     */
    @NotNull(message = "{trade.date.notnull}")
    private Date tradedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.createuserid
     *
     * @mbg.generated
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.createdatetime
     *
     * @mbg.generated
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.updateuserid
     *
     * @mbg.generated
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_trade.updatedatetime
     *
     * @mbg.generated
     */
    private Date updatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.tradeId
     *
     * @return the value of t_crm_trade.tradeId
     *
     * @mbg.generated
     */
    public String getTradeid() {
        return tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.tradeId
     *
     * @param tradeid the value for t_crm_trade.tradeId
     *
     * @mbg.generated
     */
    public void setTradeid(String tradeid) {
        this.tradeid = tradeid == null ? null : tradeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.tradeNo
     *
     * @return the value of t_crm_trade.tradeNo
     *
     * @mbg.generated
     */
    public String getTradeno() {
        return tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.tradeNo
     *
     * @param tradeno the value for t_crm_trade.tradeNo
     *
     * @mbg.generated
     */
    public void setTradeno(String tradeno) {
        this.tradeno = tradeno == null ? null : tradeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.customerNo
     *
     * @return the value of t_crm_trade.customerNo
     *
     * @mbg.generated
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.customerNo
     *
     * @param customerno the value for t_crm_trade.customerNo
     *
     * @mbg.generated
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.productNo
     *
     * @return the value of t_crm_trade.productNo
     *
     * @mbg.generated
     */
    public String getProductno() {
        return productno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.productNo
     *
     * @param productno the value for t_crm_trade.productNo
     *
     * @mbg.generated
     */
    public void setProductno(String productno) {
        this.productno = productno == null ? null : productno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.modules
     *
     * @return the value of t_crm_trade.modules
     *
     * @mbg.generated
     */
    public String getModules() {
        return modules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.modules
     *
     * @param modules the value for t_crm_trade.modules
     *
     * @mbg.generated
     */
    public void setModules(String modules) {
        this.modules = modules == null ? null : modules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.count
     *
     * @return the value of t_crm_trade.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.count
     *
     * @param count the value for t_crm_trade.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.amount
     *
     * @return the value of t_crm_trade.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.amount
     *
     * @param amount the value for t_crm_trade.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.freeServer
     *
     * @return the value of t_crm_trade.freeServer
     *
     * @mbg.generated
     */
    public Date getFreeserver() {
        return freeserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.freeServer
     *
     * @param freeserver the value for t_crm_trade.freeServer
     *
     * @mbg.generated
     */
    public void setFreeserver(Date freeserver) {
        this.freeserver = freeserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.serialnumber
     *
     * @return the value of t_crm_trade.serialnumber
     *
     * @mbg.generated
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.serialnumber
     *
     * @param serialnumber the value for t_crm_trade.serialnumber
     *
     * @mbg.generated
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber == null ? null : serialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.cdkey
     *
     * @return the value of t_crm_trade.cdkey
     *
     * @mbg.generated
     */
    public String getCdkey() {
        return cdkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.cdkey
     *
     * @param cdkey the value for t_crm_trade.cdkey
     *
     * @mbg.generated
     */
    public void setCdkey(String cdkey) {
        this.cdkey = cdkey == null ? null : cdkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.signatures
     *
     * @return the value of t_crm_trade.signatures
     *
     * @mbg.generated
     */
    public String getSignatures() {
        return signatures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.signatures
     *
     * @param signatures the value for t_crm_trade.signatures
     *
     * @mbg.generated
     */
    public void setSignatures(String signatures) {
        this.signatures = signatures == null ? null : signatures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.encryptiontype
     *
     * @return the value of t_crm_trade.encryptiontype
     *
     * @mbg.generated
     */
    public String getEncryptiontype() {
        return encryptiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.encryptiontype
     *
     * @param encryptiontype the value for t_crm_trade.encryptiontype
     *
     * @mbg.generated
     */
    public void setEncryptiontype(String encryptiontype) {
        this.encryptiontype = encryptiontype == null ? null : encryptiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.voucherpapertype
     *
     * @return the value of t_crm_trade.voucherpapertype
     *
     * @mbg.generated
     */
    public String getVoucherpapertype() {
        return voucherpapertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.voucherpapertype
     *
     * @param voucherpapertype the value for t_crm_trade.voucherpapertype
     *
     * @mbg.generated
     */
    public void setVoucherpapertype(String voucherpapertype) {
        this.voucherpapertype = voucherpapertype == null ? null : voucherpapertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.tradedate
     *
     * @return the value of t_crm_trade.tradedate
     *
     * @mbg.generated
     */
    public Date getTradedate() {
        return tradedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.tradedate
     *
     * @param tradedate the value for t_crm_trade.tradedate
     *
     * @mbg.generated
     */
    public void setTradedate(Date tradedate) {
        this.tradedate = tradedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.isdel
     *
     * @return the value of t_crm_trade.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.isdel
     *
     * @param isdel the value for t_crm_trade.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.createuserid
     *
     * @return the value of t_crm_trade.createuserid
     *
     * @mbg.generated
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.createuserid
     *
     * @param createuserid the value for t_crm_trade.createuserid
     *
     * @mbg.generated
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.createdatetime
     *
     * @return the value of t_crm_trade.createdatetime
     *
     * @mbg.generated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.createdatetime
     *
     * @param createdatetime the value for t_crm_trade.createdatetime
     *
     * @mbg.generated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.updateuserid
     *
     * @return the value of t_crm_trade.updateuserid
     *
     * @mbg.generated
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.updateuserid
     *
     * @param updateuserid the value for t_crm_trade.updateuserid
     *
     * @mbg.generated
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_trade.updatedatetime
     *
     * @return the value of t_crm_trade.updatedatetime
     *
     * @mbg.generated
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_trade.updatedatetime
     *
     * @param updatedatetime the value for t_crm_trade.updatedatetime
     *
     * @mbg.generated
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }
}